### PR TITLE
Fix regression from PR #1275

### PR DESCRIPTION
**Pull request by trwalke**
Recreating PR as I do not have permission to modify @marcre's fork

"Fix a regression from PR#1275 where if certificate.PrivateKey returns an instance of RSACryptoServiceProvider using a legacy CSP that doesn't support SHA256 the signature fails. The fix is to use the existing helper method that checks for unsupported provider types and create a new instance of RSACryptoServiceProvider with a supported provider type." - @marcre

Previous PR https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/1307

### CODE REVIEW

**Comment by trwalke** [comment]
@brentschmaltz has suggested additional changes to be made on top of @marcre's fix so those are reflected in this PR

**Comment by henrik-me** [comment]
Did you validate the original scenario?

**Comment by trwalke** [comment]
> Did you validate the original scenario?

Yes, i asked the customer to validate the fix with a private preview package.

**Comment by henrik-me** [comment]
Can we pls. ensure we have our own regression test?

**Comment by trwalke** [comment]
> Can we pls. ensure we have our own regression test?
Ok, We have a test for certs already but our test cert did not have the same properties. Basically we need to run that test multiple times with different certificate types. Ill see if I can create some certs with various private key types

**Comment by bgavrilMS** [comment]
Code look good, needs more E2E tests, potentially one for net48 as well.

**Pull request merged**
