### PR TITLE
Drop support for Mono.Android 9

### PR DESCRIPTION
**Pull request by bgavrilMS**
As per https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin

Fixes #

**Changes proposed in this request**

**Testing**

**Performance impact**

**Documentation**
- [ ] All relevant documentation is updated.

### CODE REVIEW

**Comment by SameerK-MSFT** [comment]
I would remove just MonoAndroid9.0 and TargetFrameworkAndroid9 and keep StartsWith as is. if we decide to add a version in future, this will becom future proof.
Also, are changes in "AndroidHttpClientFactory.cs" just tab changes? Ok, if they are intentional.

**Review by SameerK-MSFT — APPROVED** [review]

**Review by neha-bhargava — APPROVED** [review]

**Review by pmaytak — APPROVED** [review]
I think it will also be helpful to add the link to that Xamarin lifecycle doc to our Xamarin wiki and any Xamarin samples, with a suggestion to use Maui (unless we already do that).

**Comment by pmaytak** [comment]
> I would remove just MonoAndroid9.0 and TargetFrameworkAndroid9 and keep StartsWith as is. if we decide to add a version in future, this will becom future proof. Also, are changes in "AndroidHttpClientFactory.cs" just tab changes? Ok, if they are intentional.

If you're reviewing via browser, you can hide whitespace:
image

**Comment by bgavrilMS** [comment]
> I would remove just MonoAndroid9.0 and TargetFrameworkAndroid9 and keep StartsWith as is. if we decide to add a version in future, this will becom future proof. Also, are changes in "AndroidHttpClientFactory.cs" just tab changes? Ok, if they are intentional.

In the file yes, just tab changes. I'm guessing it's VS for Mac not applying the rule we defined in .editorconfig 
For the `StartsWith` I don't see the value, as we're never going to add support for a higher level of MonoAndroid. Maui defines Android as netX-android. "monoAndroid" is a xamarin concept and it's obsolete.

**Pull request closed without merging**
