### PR TITLE
#4605 Only include needed packages

### LINKED ISSUE #4605: Only include dependencies not provided by the framework
### Summary
The nuget packages should only have dependencies on libraries which are not provided by the framework

### Proposal
The System.Io.FileSystem.AccessControl is conditionally added based on target framework so that it is not included for the newer frameworks

### PR DESCRIPTION
**Pull request by thompson-tomo**
Fixes #4605 
**Changes proposed in this request**

- Add net 6 as TFM for Microsoft.Identity.Client.Extensions.Msal
- Make System.IO.FileSystem.AccessControl only included for Net standard 2.0 in Microsoft.Identity.Client.Extensions.Msal

**Documentation**
- [x] All relevant documentation is updated.

### CODE REVIEW

**Comment by bgavrilMS** [comment]
Hi @thompson-tomo - I understand your approach now and thank you for the time to create this. We don't want to add a new TFM to this package - it'll increase build time and we'll have to do some testing on it etc. The dependency is low risk as it's owned by the .NET team. 

Aside: I don't understand the need to remove System.Diagnostics.DiagnosticSource. This is used for MSAL to emit some metrics through Open Telemetry

**Comment by thompson-tomo** [comment]
@bgavrilMS in relation to System.Diagnostic.DiagnosticSource the new target framework's natively provide the library hence the explicit package reference is not needed.

**Comment by bgavrilMS** [comment]
> @bgavrilMS in relation to System.Diagnostic.DiagnosticSource the new target framework's natively provide the library hence the explicit package reference is not needed.
> 
> For the additional TFM to eliminate an explicit dependency, I wonder how much testing would be needed given said package is extremely likely to be the same as the provided by the framework. This is the case based on the fact that the package has not been updated in quite a whil3.

Ok, you make a good point. Can you please leave just the TFM changes in there, i.e. do not include the System.Diagnostics removal?

**Comment by bgavrilMS** [comment]
@neha-bhargava - a heads up for System.Diagnostics.

**Comment by thompson-tomo** [comment]
@bgavrilMS change made as requested and have been pushed.

**Review by bgavrilMS — APPROVED** [review]

**Review by pmaytak — APPROVED** [review]

**Pull request merged**
