### PR TITLE
[Suggestion] Fix two issues with dSTS authority, one when using WithTenantId, and …

### LINKED ISSUE #4144: [Bug] When using .WithTenantId() with a dSTS authority, get `tenant_override_non_aad` error
Based on testing from @JoshLozensky with Id Web and a dSTS authority, we are getting:

```Unhandled exception. MSAL.NetCore.4.52.0.0.MsalClientException:
        ErrorCode: tenant_override_non_aad
Microsoft.Identity.Client.MsalClientException: WithTenantId can only be used when an AAD authority is specified at the application level.
   at Microsoft.Identity.Client.AbstractAcquireTokenParameterBuilder`1.WithTenantId(String tenantId)
   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForAppAsync(String scope, String authenticationScheme, String tenant, TokenAcquisitionOptions tokenAcquisitionOptions)
   at Microsoft.Identity.Web.DefaultAuthorizationHeaderProvider.CreateAuthorizationHeaderForAppAsync(String scopes, AuthorizationHeaderProviderOptions downstreamApiOptions, CancellationToken cancellationToken)
   at Microsoft.Identity.Web.DownstreamApi.CallApiInternalAsync(String serviceName, DownstreamApiOptions effectiveOptions, Boolean appToken, HttpContent content, ClaimsPrincipal user, CancellationToken cancellationToken)
   at Microsoft.Identity.Web.DownstreamApi.GetForAppAsync[TOutput](String serviceName, Action`1 downstreamApiOptionsOverride, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\workingDirectory\MicrosoftIdentityClientInternal\Samples\daemon-console\daemon-console\Program.cs:line 29
   at Program.<Main>(String[] args)
```
   
   Because MSAL is not including dSTS in the [tenant override](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/18fc3525d06dfe964c7290d8ee10e538f3e58f4d/src/client/Microsoft.Identity.Client/AppConfig/AuthorityInfo.cs#L141), only AadAuthority:
   
`internal bool IsTenantOverrideSupported => AuthorityType == AuthorityType.Aad;`

### LINKED ISSUE #4145: [Bug] When using dSTS authority with WithTenantId & have applied fix from: #4144, get cast error
Unable to cast object of type 'Microsoft.Identity.Client.Instance.DstsAuthority' to type 'Microsoft.Identity.Client.Instance.AadAuthority'.

On this line: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/main/src/client/Microsoft.Identity.Client/ApiConfig/AbstractAcquireTokenParameterBuilder.cs#L277

If a dSTS authority is used, the code is casting for an AadAuthority, but AuthorityInfo is dSTS, so the cast fails:

`AadAuthority aadAuthority = (AadAuthority)ServiceBundle.Config.Authority;` 

You have a test checking for dSTS authority types [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/18fc3525d06dfe964c7290d8ee10e538f3e58f4d/tests/Microsoft.Identity.Test.Unit/ApiConfigTests/AuthorityTests.cs#LL116C22-L116C22), but it's using [WithTenantIdFromAuthority](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/18fc3525d06dfe964c7290d8ee10e538f3e58f4d/src/client/Microsoft.Identity.Client/ApiConfig/AbstractAcquireTokenParameterBuilder.cs#L301 which is not what we use in Id Web, we use `.WithTenantId()`.

### PR DESCRIPTION
**Pull request by jennyf19**
…adding dSTS as a supported tenant override. Add a test

Fixes #4144, fixes #4145 

Just a suggestion. I'm having issues running the MSAL tests, so assuming this would work. have tested E2E with Id Web and seems to be working.

### CODE REVIEW

**Review by bgavrilMS — APPROVED** [review]
Generalized a bit the logic and made the unit test handle the other tenant id

**Comment by bgavrilMS** [comment]
PR status seems ok, some CIAM tests are failing due to invalid secret. @gladjohn - should we disable these tests as well?

**Comment by jennyf19** [comment]
I will let you merge the PR when the other tests are fixed. Thanks.

**Review by gladjohn — APPROVED** [review]

**Comment by gladjohn** [comment]
> I will let you merge the PR when the other tests are fixed. Thanks.

tests are passing now. Once @neha-bhargava approves we will merge this

**Review by neha-bhargava — APPROVED** [review]
Looks good. Thanks @jennyf19

**Pull request merged**
