### PR TITLE
Hide 2 APIs which are only for 1p

### LINKED ISSUE #3670: Page should define MSAPassThrough
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#31140](https://github.com/Azure/azure-sdk-for-net/issues/31140).

## Details

I came to the page to figure out what this property does and is used for.  The current description didn't help much.  What is MSA? Why do Legacy Applications need it?  

More information to help the developer make an informed decision would be super useful.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af97da54-d81f-8cc1-8a1a-ba10ed5dc41b
* Version Independent ID: c82c4c28-89a1-950f-2b58-b1795045f54c
* Content: [WindowsBrokerOptions.MsaPassthrough Property (Microsoft.Identity.Client) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.windowsbrokeroptions.msapassthrough?view=azure-dotnet)
* Content Source: [xml/Microsoft.Identity.Client/WindowsBrokerOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Identity.Client/WindowsBrokerOptions.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

### PR DESCRIPTION
**Pull request by bgavrilMS**
Fixes #3670

**Changes proposed in this request**

**Testing**

**Performance impact**

**Documentation**
- [ ] All relevant documentation is updated.

### CODE REVIEW

**Review by jmprieur — APPROVED** [review]
LGTM
Thanks @bgavrilMS

**Review by SameerK-MSFT — APPROVED** [review]

**Review by gladjohn — APPROVED** [review]
looks good. Should we also add WithRegion to this list?

**Review by pmaytak — COMMENTED** [review]
Wouldn't hiding add confusion to the 1p app developers? Jus thinking of edge cases and anticipating questions like, "I'm trying to add multi cloud support, but the method is not there...".

Maybe just a comment remark explicitly saying this is only avaiable to internal Microsoft applications is sufficient.

**Comment by bgavrilMS** [comment]
> Wouldn't hiding add confusion to the 1p app developers? Jus thinking of edge cases and anticipating questions like, "I'm trying to add multi cloud support, but the method is not there...".
> 
> Maybe just a comment remark explicitly saying this is only avaiable to internal Microsoft applications is sufficient.

These seem to create problems for docs.

**Pull request merged**
