### PR TITLE
Move some exception classes and update .gitignore

### PR DESCRIPTION
**Pull request by bgavrilMS**

### CODE REVIEW

**Comment by MarkZuber** [comment]
I had actually moved the exceptions to root in an effort for starting to have our public API and our layout actually match our directory structure.  And since the public exceptions are in Microsoft.Identity.Client, I moved them out of the exceptions directory.  What do you think?

**Comment by bgavrilMS** [comment]
Yes, I agree that we should be closer to what the tool (VS) proposes. There may be quite a few classes in the "root", maybe having an msal.Exceptions namespace would work ?

**Comment by MarkZuber** [comment]
> Yes, I agree that we should be closer to what the tool (VS) proposes. There may be quite a few classes in the "root", maybe having an msal.Exceptions namespace would work ?

Agree we could have a namespace but that would be a breaking change to the public API.

**Comment by bgavrilMS** [comment]
Oh yes, of course, disregard that :)

**Pull request closed without merging**
