### PR TITLE
Small change to release build on usage of .NET SDK

### PR DESCRIPTION
**Pull request by bgavrilMS**

### CODE REVIEW

**Review by trwalke — APPROVED** [review]
LGTM. Running a release build targeting this branch just to verify. 
Approval upon successful release build.

**Review by trwalke — CHANGES_REQUESTED** [review]
Release build has failed. may have to reinstall net core 3 and then switch to .net core 2 just before signing. or try installing both at the start of the build

https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=733389

**Comment by jmprieur** [comment]
We can install both .NET Core 3.* and .NET Core 2.

**Review by trwalke — APPROVED** [review]

**Comment by bgavrilMS** [comment]
Thx for checking @trwalke ! I fixed the issue and this all builds now: https://identitydivision.visualstudio.com/IDDP/_build?definitionId=907&_a=summary

**Pull request merged**
