### PR TITLE
Remove Newtonsoft

### PR DESCRIPTION
**Pull request by MichelZ**
**Changes proposed in this request**
Replace Newtonsoft Json references with Microsoft.Identity.Client.Json implementation for consistency

Not sure if that's wanted or not, but I thought it makes sense

### CODE REVIEW

**Comment by bgavrilMS** [comment]
For test projects we probably want to use System.Text.Json ... For MSAL itself it's more complicated, but there is a separate work item tracking it and someone is looking at it.

**Review by bgavrilMS — CHANGES_REQUESTED** [review]
We should use System.Text.Json instead of Newtonsoft if possible. A project reference is better than direct refrence for test projects, because in case of security issues we will be updated.

**Comment by bgavrilMS** [comment]
Is it ok to close this? I think we can let the existing projects as they are.

**Comment by MichelZ** [comment]
Sure :)

**Pull request closed without merging**
