### PR TITLE
Fixed binary injection script.

### PR DESCRIPTION
**Pull request by HSAR**
Changed "mv" command to "copy" and removed a copy step at the beginning - this is now done as a build step in VSTS.

Thanks to @jennyf19 for spotting this problem.

### CODE REVIEW

**Comment by kpanwar** [comment]
@HSAR - have you verified that the final nuget has signed binaries?

**Comment by HSAR** [comment]
@kpanwar I have. I downloaded the uploaded package, extracted out `/lib/net45/Microsoft.Identity.Client.dll` and used `sn.exe -vf Microsoft.Identity.Client.dll` which returned that the DLL is valid.

Although I should note that this is how I checked before.

**Comment by kpanwar** [comment]
@HSAR - that is not the right way. MSAL snk is a known key checked in the repo. What  you need to check is the authenticode signature. You can do that by checking DLL properties

**Comment by HSAR** [comment]
There's not a very good way to return an error code if things fail, @kpanwar. There is a "last error code" variable that is set after every command, but in order to act on it we would need to add a new if statement after every single command call :(

**Comment by HSAR** [comment]
Okay, second try @kpanwar. This script only seems to create a *.symbols.nuget package, is that expected?

**Pull request merged**
