### PR TITLE
Remove MacCatalyst

### LINKED ISSUE #3693: [Bug] Remove MacCatalyst from package
**Logs and network traces**
NA

**Which version of MSAL.NET are you using?**
4.47.0

**Platform**
MAUI

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**
New

**Repro**
The package lib for MacCatalyst. It is not supported.

### PR DESCRIPTION
**Pull request by SameerK-MSFT**
Fixes #3693

**Changes proposed in this request**
Removed Target Framework for MacCatalyst

**Testing**
Manually test apps and inspect the package

**Performance impact**
None

**Documentation**
- [ ] All relevant documentation is updated.

### CODE REVIEW

**Comment by bgavrilMS** [comment]
What is the dev ex now if I try to use a mac catalyst app? Can we provide a decent error message?

**Comment by pmaytak** [comment]
More details in the associated issue #3527 should be added - what specifically needs to be done to enable support, what are the blockers.

**Review by gladjohn — APPROVED** [review]
Approving but please make sure to remove other references for `TargetFrameworkNet6Mac` from the csproj file

**Comment by SameerK-MSFT** [comment]
> Approving but please make sure to remove other references for `TargetFrameworkNet6Mac` from the csproj file
It is harmless. There is no time now to cleanup. Created issue.
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3726

**Pull request merged**
