### PR TITLE
Add SubError in the Android Broker

### PR DESCRIPTION
**Pull request by SameerK-MSFT**
Fixes #
Changes for Intune

**Changes proposed in this request**
Added SubError from the brtoker

**Testing**
Manual

**Performance impact**
None

**Documentation**
- [x] All relevant documentation is updated.
NA

### CODE REVIEW

**Comment by bgavrilMS** [comment]
Is this still relevant Sameer?

**Comment by SameerK-MSFT** [comment]
> Is this still relevant Sameer?

It works w/o this as confirmed by client. But this can be a safety net/defensive programming, just in case something happens.

**Comment by bgavrilMS** [comment]
> > Is this still relevant Sameer?
> 
> It works w/o this as confirmed by client. But this can be a safety net/defensive programming, just in case something happens.

Not sure I understand how it's a safety net? Are we doing anything with that property? Do we want to log its value at least?

**Comment by bgavrilMS** [comment]
Closing, please reopen if neeeded.

**Pull request closed without merging**
