### PR TITLE
Used multiple ARM API versions for subscriptions/get in WwwAuthenticateParametersIntegrationTests

### PR DESCRIPTION
**Pull request by abatishchev**
**Changes proposed in this request**

Currently ARM API for subscriptions/get supports multiple API versions, this PR updates the one used to the currently latest.

**Testing**

Yes, the PR updates the integration tests only.

**Performance impact**

No perf impact.

**Documentation**

<s>- [ ] All relevant documentation is updated.</s>

### CODE REVIEW

**Comment by abatishchev** [comment]
@bgavrilMS I can update the tests to try multiple API versions, just to increase the coverage.

**Review by bgavrilMS — APPROVED** [review]

**Comment by bgavrilMS** [comment]
> @bgavrilMS I can update the tests to try multiple API versions, just to increase the coverage.

Are there different formats of the WWW-AUthenticate header?

**Comment by abatishchev** [comment]
@bgavrilMS no, the only difference is in the API version when it calls ARM API. Which strives on backward compatibility, so I don't expect a different outcome or behavior per API version

**Comment by bgavrilMS** [comment]
> @bgavrilMS no, the only difference is in the API version when it calls ARM API. Which strives on backward compatibility, so I don't expect a different outcome or behavior per API version

Then I think we are good.

**Comment by abatishchev** [comment]
@bgavrilMS it's ready for a re-review

**Review by bgavrilMS — APPROVED** [review]

**Comment by bgavrilMS** [comment]
Tested this locally.

**Pull request merged**
