### PR TITLE
GH-1653 AndroidX Support

### PR DESCRIPTION
**Pull request by jamesmontemagno**
#1653

Updated to build for Android 9 and Android 10.

Android 10 supports AndroidX work including the services.

Work to be done would be test integration. This should be easily accomplished by creating 2 head projects. One compiles against 9 and one against 10.

### CODE REVIEW

**Comment by bgavrilMS** [comment]
Will take a look as soon as possible. @jamesmontemagno - I assume the best way to test this is to have an app target Android 9 and then move to Android 10 to see the migration?

**Comment by jamesmontemagno** [comment]
Yeah, There is a built in migration tool too: https://docs.microsoft.com/en-us/xamarin/android/platform/androidx

When you have the latest Xamarin.Forms (4.5) and re-target to compile against 10.0 using PackageReferences it will use AndroidX at the core.

**Comment by neha-bhargava** [comment]
@jamesmontemagno  I performed the testing on emulator and it works as expected for embedded web view. But seems like the system browser (chrome) does not have custom tabs. Is it something known with AndroidX?

**Comment by jamesmontemagno** [comment]
I mean it could be possible I missed something in there... 

I did add: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/1745/files#diff-9aef39af4a36c0197ee96e49281fcf9cR40 but yeah that should work to open it.

**Comment by jamesmontemagno** [comment]
Should be fixed up, basically ADAL does a check to see if anything can open a custom tab and if not then don't do anything. We have to use the older check.

**Comment by neha-bhargava** [comment]
> Should be fixed up, basically ADAL does a check to see if anything can open a custom tab and if not then don't do anything. We have to use the older check.

There was a check in the app I was using but should not the custom tabs be available anyway? I am using an emulator and the browser is chrome.

**Comment by jamesmontemagno** [comment]
I mean technically users could remove browsers that don't support chrome custom tabs.

In that case it defaults back to non-custom tabs. I am not sure I am in love with this check, but I didn't put it there :)

**Comment by bgavrilMS** [comment]
The phone not having a browser that supports custom tabs is a known issue. There are some phone manufacturers that ship Android phones with such browsers. I believe we have a method called "IsSystemWebViewAvailable" that makes this check

For now, the important thing is that this works on phones with Chrome installed. A second test is to try what happens with Chrome uninstalled - I'd expect a nice exception and that flag to be false. @jennyf19 can confirm this.

**Comment by jennyf19** [comment]
Things should work without custom tabs, here's a list of [browsers](https://github.com/azuread/microsoft-authentication-library-for-dotnet/wiki/Android-system-browser) and their results, this is from a year or two ago, however.
I haven't read through this issue though, if you want me to do so, lmk.

**Comment by jamesmontemagno** [comment]
Correct all of those browser support custom tabs which my change does nothing beside upgrade to the android x version of the library. So whatever worked before should continue to work.

**Comment by bgavrilMS** [comment]
Thanks @jamesmontemagno - we'll have a look at retesting

**Comment by jennyf19** [comment]
Thanks @jamesmontemagno I'll pull your branch and take a look.

**Comment by jennyf19** [comment]
@jamesmontemagno We had some issues w/our test app, which have sorted out now. 
This PR looks good to me. We need to test one more scenario (android + broker).

One question, for you, if I have two apps w/the same clientId, redirectUri, and android scheme on the same device, right now, when using system browser, I get a pop-up asking me which app I want to open. With Android X updates, I'm not seeing that pop-up. Is this expected?
image

**Comment by jamesmontemagno** [comment]
@redth any thoughts^?

**Comment by bgavrilMS** [comment]
@jennyf19 - in your scenario with 2 apps using the same redirect uri, what is the behavior on Android X? Does it freeze?

**Comment by jennyf19** [comment]
@bgavrilMS it just tries to open one of the two apps, so the user doesn't get to select which one, and the user is shown a blank screen.

**Comment by jamesmontemagno** [comment]
When you have multiple apps using the same redirect you should see the pop up from the OS. However, if you already selected one once it may have it selected as the default.

That is just android base OS level and the AndroidX package for chrome custom tabs wouldn't really have any impact there is my thinking.

**Comment by jennyf19** [comment]
@jamesmontemagno that makes sense. I guess you'd go into settings to remove the pre-selected app? just so we can document this better.

**Comment by jennyf19** [comment]
@bgavrilMS @jamesmontemagno I resolved the merge conflict. i think this is ready to go unless we want to test broker first. i don't think it matters too much either way, as we can resolve any issues as they come up if needed. my 2 cents.

**Comment by bgavrilMS** [comment]
Propose to merge and test the broker scenarios as part of our release testing.

**Comment by bgavrilMS** [comment]
Merging this as it will improve our testing.

**Pull request merged**
