### PR TITLE
Comprehensive spellcheck

### PR DESCRIPTION
**Pull request by JosefPihrt**
**Changes proposed in this request**
I used a Roslyn-based tool to scan code base for misspellings and typos and fix it.

**Testing**
none

**Performance impact**
none

### CODE REVIEW

**Comment by pmaytak** [comment]
Thanks @JosefPihrt, which tool is it? Maybe we can add so it runs automatically.

Gave a quick look - anything in 'json' folder can be disregarded; also some public members were changed, which should be kept the same.

**Review by bgavrilMS — APPROVED** [review]

**Comment by bgavrilMS** [comment]
@JosefPihrt - can you please sign the [Contributor License Agreement](https://cla.opensource.microsoft.com/AzureAD/microsoft-authentication-library-for-dotnet?pullRequest=3378) that the bot requested? It is a requirement for us to be able to merge your change.

**Comment by JosefPihrt** [comment]
@bgavrilMS signed

**Comment by JosefPihrt** [comment]
@pmaytak I use Roslynator command-line tool.

https://github.com/JosefPihrt/Roslynator/blob/master/docs/cli/spellcheck-command.md

**Comment by pmaytak** [comment]
Merged into my feature branch so PR builds car run.

**Comment by bgavrilMS** [comment]
Thanks for your contribution @JosefPihrt !!

**Comment by JosefPihrt** [comment]
@bgavrilMS It was a pleasure!

**Pull request merged**
