### PR TITLE
spelling + spacing fixes to msal error messages

### PR DESCRIPTION
**Pull request by jennyf19**
done while starting #2083

### CODE REVIEW

**Review by pmaytak — APPROVED** [review]

**Review by jmprieur — APPROVED** [review]
LGTM
Thanks @jennyf19.

Is, adding a space in the end, to make the logs clearer ?

**Comment by bgavrilMS** [comment]
Looks like this breaks some unit tests. We should probably not assert on error messages, only on error codes.

**Comment by jennyf19** [comment]
Yes. when all the logs are together it can be super hard to read. i'll maybe do another PR w/more fixes like that. 

---
In reply to: [533190058](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/2202#issuecomment-533190058) [](ancestors = 533190058)

**Comment by jennyf19** [comment]
I didn't even think to run the unit tests. lol. fixed.

---
In reply to: [729702492](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/2202#issuecomment-729702492) [](ancestors = 729702492)

**Pull request merged**
