### PR TITLE
Add nbgv git versioning

### PR DESCRIPTION
**Pull request by sangonzal**
Not ready to be merged yet, but this review is so that everyone can see how nbgv git versioning works and decide if we'd like to use it:

Instructions on how to use the nbgv .NET CLI tool: https://github.com/AArnott/Nerdbank.GitVersioning/blob/master/doc/nbgv-cli.md

### CODE REVIEW

**Comment by henrik-me** [comment]
pls. ensure this is fully integrated into the build system. Bogdan and Mark should sign-off.

**Comment by henrik-me** [comment]
@MarkZuber @bgavrilMS : would be great to get your perspective on this one.

**Comment by MarkZuber** [comment]
I'd like to try this out.  The code/changes look fine and reasonable from previous git versioning experiences.  I'm most curious how this integrates with VSTS and whether it can publish its build information to VSTS for consistency (e.g. the build numbers on VSTS show up as the build numbers generated by nbgv).  This worked when I worked with GitVersion and you had to specify your build engine.  Given this is built by AArnott (who works at msft) I'd expect it to integrate well with vsts but i'm not sure if there's more work for us to do.  I'm going to sign off on the PR since the code looks fine but I'd like to talk about how we test/integrate this with the builds before we merge it.  Can we try enabling it on this branch to see how it works?

Also, I think we should wait until we do 2.6.1 with Jenny's pending changes for VS before this hits master because I don't want to block 2.6.1 on getting this working.

**Comment by sangonzal** [comment]
Yep, I think the plan is to to test the integration on Azure DevOps on this branch before merging to master (It's supported, but have not tried it yet). I talked to  @bgavrilMS offline, and there were some requirements around naming that we'd like to keep (e.g, we'd like to keep them in chronological order on myget), so he wanted to test it locally before proceeding. Once that's done, we can test integration with Azure DevOps.

The version is pulled from the version.json, the git height, and the git commit id. Doesn't seem like you can use branch tags, but I'm not 100%. The output looks something like this: 

Version:             2.6.0.2
AssemblyVersion:              2.6.0.0
AssemblyInformationalVersion: 2.6.0-preview.2+g4ebf621adc
NuGet package Version:        2.6.0-preview.2.g4ebf621adc

You would drop the git height and commit id for release builds.

**Comment by bgavrilMS** [comment]
I expanded a bit your work to make sure both DLLs and NuGet packages are versioned. It created a new PR for this, since this one is quite old and would have required a lot of rebasing

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/749

**Pull request closed without merging**
