### PR TITLE
Create mockable AcquireToken calls

### PR DESCRIPTION
**Pull request by MarkZuber**
Based on customer feedback our I[Public|Confidential]Client interfaces aren't mockable due to the way the fluent API works.  This is a proposal to enable mockability that we can discuss.

Currently missing API documentation until we lock on the decision of how to proceed here.

### CODE REVIEW

**Comment by henrik-me** [comment]
Makes a lot of sense to do this instead as testability is certainly important.
Aside: Was thinking if we can also wrap the ConfigureAwait(false) into the call and make it the default behavior with an option to specify true/false and/or even with allow developers to specify configureAwait them selves... ? tldr: looking for a way to default to the simple pattern? (though not advised in some scenarios but mostly that is what should be done), thoughts?

**Comment by henrik-me** [comment]
Crazy suggestion:.. + ExecuteAwaitAsync + ExecuteNoAwaitAsync

---
In reply to: [474122091](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/988#issuecomment-474122091) [](ancestors = 474122091)

**Comment by MarkZuber** [comment]
No, you can't do that.  the async usage analyzers look at it on the call to the method that returns a Task<T> so you'd fail those roslyn analyzers.  We unfortunately can't bake this in.

---
In reply to: [474122621](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/988#issuecomment-474122621) [](ancestors = 474122621,474122091)

**Comment by henrik-me** [comment]
ack

---
In reply to: [474124395](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/988#issuecomment-474124395) [](ancestors = 474124395,474122621,474122091)

**Comment by jmprieur** [comment]
Does it change the way the developer uses the API? (I don't this it does, but I did not really understand what is different)

**Pull request closed without merging**
