### PR TITLE
Remove WithExperimentalAPI from WAM

### PR DESCRIPTION
**Pull request by bgavrilMS**
Issue #2700.

Will need to update https://aka.ms/msal-net-wam docs 
This just removes WithExperimentalFeatures

### CODE REVIEW

**Review by jennyf19 — APPROVED** [review]

**Review by pmaytak — CHANGES_REQUESTED** [review]
I think we need to remove it from here also. I can push the change.
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/f8195baa93003587092aa1d8a2fb0ad78f759286/src/client/Microsoft.Identity.Client.Desktop/WamExtension.cs#L19-L24

**Review by pmaytak — COMMENTED** [review]
Pushed a commit to remove experimental features check in `WamExtensions.WithWindowsBroker` in Msal.Desktop.

Also I can update the WAM wiki once this is merged.

**Review by neha-bhargava — APPROVED** [review]

**Review by jmprieur — APPROVED** [review]
LGTM
We'd also want to update the samples using WAM:
- https://github.com/Azure-Samples/active-directory-dotnet-desktop-msgraph-v2/blob/da9b6673b0cefef430f5228ba985490441e0a8e6/active-directory-wpf-msgraph-v2/App.xaml.cs#L28

**Comment by bgavrilMS** [comment]
Thanks @pmaytak

**Review by pmaytak — APPROVED** [review]

**Pull request merged**
