### PR TITLE
Update PublicClientApplicationBuilder.cs

### PR DESCRIPTION
**Pull request by henrik-me**
updating the reference doc for default resply uri for netcore

### CODE REVIEW

**Review by jmprieur — APPROVED** [review]
LGTM. Thanks @henrik-me

**Comment by henrik-me** [comment]
@trwalke @bgavrilMS : UI automation seems to continuously fail. Thoughts? Is this tracked somewhere?

**Comment by trwalke** [comment]
@henrik-me  This is looking like an issue with the environment. It appears that all of the ADFS tests are timing out when loading the sign in page.
image

As you can see in the image, the page is not loading correctly. 

Unfortunately, the reruns are also failing for these so ill reach out to the lab to see what the status of the environment is.

**Review by trwalke — APPROVED** [review]
LGTM

**Review by neha-bhargava — APPROVED** [review]
👍

**Comment by trwalke** [comment]
@henrik-me seems like the issue is resolved for the ui automation tests. Appears to be a temporary outage. All tests are green

**Comment by henrik-me** [comment]
> @henrik-me seems like the issue is resolved for the ui automation tests. Appears to be a temporary outage. All tests are green

I reran these tests many times... seems like adfs test environments are more unreliable than other tests, then?

**Comment by neha-bhargava** [comment]
Fixed in [MSAL 4.21.0 rellease](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.21.0).

**Pull request merged**
