### PR TITLE
Use sub claim if oid is missing

### LINKED ISSUE #4140: [Bug] SerializeAdalV3 returns null when Id Token has no oid claim
Scenario: web site

This is an ADAL 2 MSAL migration issue. Partner is using `SerializeAdalV3` logic which in some cases returns null. This caused the partner to revert back from MSAL to ADAL.

 It looks like in rare cases the IdToken does not have `oid` claim. ADAL uses `sub` claim when `oid` is not available.

### PR DESCRIPTION
**Pull request by bgavrilMS**
Fixes #4140

### CODE REVIEW

**Review by jmprieur — COMMENTED** [review]
LGTM
Was GetUniqueId() already defined?

**Comment by bgavrilMS** [comment]
> LGTM Was GetUniqueId() already defined?

Yeah, it's used to compute `AuthenticationResult.UniqueId` which is public API. I changed the comments on it.

**Comment by gladjohn** [comment]
```cs
public string GetUniqueId()
{
    return ObjectId ?? Subject;
}
```

what does subject return?

**Review by neha-bhargava — APPROVED** [review]

**Review by pmaytak — APPROVED** [review]

**Review by trwalke — APPROVED** [review]

**Review by rayluo — APPROVED** [review]

**Review by jmprieur — APPROVED** [review]

**Comment by bgavrilMS** [comment]
> ```cs
> public string GetUniqueId()
> {
>     return ObjectId ?? Subject;
> }
> ```
> 
> what does subject return?

sub claim. I added comments everywhere on this. Seems to be mandatory as per OIDC spec. Should be an ID for app + user, but  can theoretically be different for app2 + user. Stable enough for token caching for sure.

**Pull request merged**
