### PR TITLE
Add the public API analyzer

### LINKED ISSUE #4931: [Feature Request] Public API analyzer integration
### MSAL client type

Public, Confidential, Managed identity

### Problem statement

[Public_API_Analyzer.md - Repos (visualstudio.com)](https://identitydivision.visualstudio.com/DevEx/_git/MISE?path=/internaldocs/Public_API_Analyzer.md&version=GBmaster&_a=preview)

Mise and Sal have this already.

### Proposed solution

_No response_

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by bgavrilMS**
Fixes #4931

**Changes proposed in this request**

**Testing**

**Performance impact**

**Documentation**
- [ ] All relevant documentation is updated.

### CODE REVIEW

**Comment by trwalke** [comment]
Shouldn't the "Desktop, Broker, Extension" projects also have a separate folder for each target framework?

**Review by trwalke — APPROVED** [review]

**Comment by bgavrilMS** [comment]
Well MSAL doesn't use nullable references feature. We can add it, but that's a work item in itself and a I imagine pretty big one.

**Comment by bgavrilMS** [comment]
> Well MSAL doesn't use nullable references feature. We can add it, but that's a work item in itself and a I imagine pretty big one.

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/5014

**Comment by bgavrilMS** [comment]
Ignoring `BuildQualityChecks` as there is no code in this PR.

**Pull request merged**
