### PR TITLE
Changed test project to match VS2017 template

### PR DESCRIPTION
**Pull request by duncanpMS**
Changed test project to match VS2017 template
Changed build script to build the test project

### CODE REVIEW

**Comment by kpanwar** [comment]
@onovotny - can you also take a look? I remember you saying that packages.config should not be used for projects. Instead we can use LSP2Workaround nuget and use ProjectReference

**Comment by onovotny** [comment]
I would not do it like this. If you want a new test template, I'd use the new template based on the SDK style projects. It'd be similar to this https://github.com/Reactive-Extensions/Rx.NET/blob/develop/Ix.NET/Source/Tests/Tests.csproj, but with MSTest refs instead of xUnit.

You can use `dotnet new mstest` to generate a skeleton project.

**Comment by onovotny** [comment]
To build the project, you can use `dotnet test --no-build` after a build since `dotnet test` cannot currently handle the `GitVersionTask` targets. Using `--no-build` solves this since test won't execute a build first (you'll have built it with msbuild /t:build already anyway)

**Comment by onovotny** [comment]
Also, not sure why you want to specify `TargetFrameworks` as an input parameter. It's already in one place in the project file: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/243/files#diff-4fc42a4893bd8bfcfed6337f79edf5a0L26

The tests cannot have it that way because those can only be `net452`+ or `netcoreapp1.0`+. If you wan to run unit tests on iOS or Android, then you need the xUnit for Devices projects and those need to be separate "app test projects". http://xunit.github.io/docs/getting-started-devices.html

**Comment by duncanpMS** [comment]
@onovotny TargetFramework: I thought I'd added a comment about the Android build in this PR, but that was in the previous PR. The goal of these changes is to enable building the projects using AppVeyor so we can automatically validate PRs. AppVeyor doesn't currently support the required version of Android. The script passes in the list of _TargetFrameworks_ to override property in the project.
However, it doesn't need to be set for the test project, so I'll remove that setting.

**Comment by onovotny** [comment]
AppVeyor should have all Android versions installed -- if not, I can reach out to the AppVeyor team to remedy. What issue are you seeing there?

**Comment by kpanwar** [comment]
@onovotny - I am quite jealous of the reach you have across various product teams. :) We are seeing that API24 is not installed in the build environments that causes android to fail.

**Comment by onovotny** [comment]
@kpanwar AppVeyor isn't a Microsoft product, but they do respond to issues about what's in their images. I posted this here: https://github.com/appveyor/ci/issues/1411#issuecomment-287576171

**Comment by onovotny** [comment]
@kpanwar looks like there's a workaround you can add to your AppVeyor.yml until they install API 24 and 25:

https://github.com/appveyor/ci/issues/1411#issuecomment-287678065

**Comment by duncanpMS** [comment]
@onovotny Thanks for the Android workaround. I haven't included in this PR as it's a separate issue.

**Comment by duncanpMS** [comment]
Relates to issue #180

**Pull request merged**
