### PR TITLE
Fixed coding style: Avoid "this." unless absolutely necessary.

### PR DESCRIPTION
**Pull request by oriain**
- https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md

### CODE REVIEW

**Comment by kpanwar** [comment]
@oriain - please resolve conflicts

**Comment by oriain** [comment]
@kpanwar When I submitted this pull request, Github showed the code could automatically be merged with the dev branch.  Is there anything written about how pull requests are processed for this repo?  This was a simple refactor, yet for some reason it was held up even when three later pull requests were approved and merged.  The merge conflicts are are a result of that delay; it would be nice to know if there is something I could do in the future to avoid this type of extra work.

**Comment by kpanwar** [comment]
@oriain - PRs are not reviewed in FIFO order. We do it based on priority and sometimes complexity. We also do not guarantee a immediate turn around for external PRs. You are more than welcome to file an issue instead and we can prioritize in our backlog.

**Comment by oriain** [comment]
Thanks for the prompt merge!  And before I could even let you know I resolved the merge conflicts.

It would be nice to have the information regarding processing PRs based on priority and complexity in the contributing guidelines for the repository.  Currently it only mentions that pull requests are usually reviewed within a few days, but nothing about the order in which they are approved or merged.

In any case, thanks!

**Pull request merged**
