### PR TITLE
Enable system browser on xamarin macos

### PR DESCRIPTION
**Pull request by bgavrilMS**
The default remains the embedded browser

### CODE REVIEW

**Comment by henrik-me** [comment]
>     internal class TcpInterceptor : ITcpInterceptor

As you are in this area... I think adding more logging may be needed based on discussions we had earlier today?

---
Refers to: src/client/Microsoft.Identity.Client/Platforms/Shared/DefaultOSBrowser/TcpInterceptor.cs:23 in d224a6f. [](commit_id = d224a6fa32ef0f363c0e26514a5372982585cbb5, deletion_comment = False)

**Comment by henrik-me** [comment]
Consider if we can add logging to understand why we would not be getting the callback (based on the redirect uri)

**Comment by henrik-me** [comment]
Aside: Seems like the non yaml build stuff can be removed

**Comment by bgavrilMS** [comment]
Add more logging.

**Pull request merged**
