### PR TITLE
Use Release configuration.

### PR DESCRIPTION
**Pull request by pmaytak**
**Changes proposed in this request**
In previous PR the build configurations were refactored, the config was changed from Debug to Release in some places. So I updated to use Release everywhere. Plus my guess is maybe it'll make the builds faster too?

### CODE REVIEW

**Review by bgavrilMS — APPROVED** [review]

**Comment by trwalke** [comment]
what is the reason for this?

**Comment by pmaytak** [comment]
> what is the reason for this?

@trwalke In previous PR where Bogdan refactored the build configurations,  the config was changed from Debug to Release in some places. So I updated to use Release everywhere. Plus my guess is maybe it'll make the builds faster too?

**Comment by gladjohn** [comment]
Should the android failure be addressed along with this? would be nice to pass build configuration parameter so we do not hardcode debug|Release in test path

**Review by gladjohn — APPROVED** [review]

**Review by neha-bhargava — APPROVED** [review]

**Review by trwalke — APPROVED** [review]

**Comment by pmaytak** [comment]
> Should the android failure be addressed along with this? would be nice to pass build configuration parameter so we do not hardcode debug|Release in test path

Yeah, but I just wanted to quickly fix the build without refactoring anything.

**Pull request merged**
