### PR TITLE
Update msal-3x-blog.md

### PR DESCRIPTION
**Pull request by bgavrilMS**

### CODE REVIEW

**Comment by bgavrilMS** [comment]
I only managed to read until the "Summarizing the feedback" section. I doubt anybody will read such a long article. I suggest separating the rest into an article that is very punctual (none of the story of "why we did this") and focused more on code.

**Comment by jmprieur** [comment]
Thanks @bgavrilMS : the issue is the first part was exposing problems, and the second part the solutions. Now you seem to suggest to intermix problems with solutions ?

**Comment by henrik-me** [comment]
> This paragraph explains why MSAL.NET's major version number was bumped-up from 2 to 3. If you are new to MSAL.NET or are not interested in the reasons for changing the API, you might want to skip to [changes in MSAL.NET 3.x](#changes-in-msalnet-3x).

I think in that case the user would want to skip even further. Personally I would not read that if I'm new and just starting using the library.

---
Refers to: msal-3x-blog.md:23 in 7461abd. [](commit_id = 7461abd13fea44bb9cb457be6b8ea62a4dfe0540, deletion_comment = False)

**Comment by jennyf19** [comment]
> 

I think @bogavril@microsoft.com is on the right track, but i also see the value in having a verbose blog post. I guess it comes down to who is our target audience(s)? Maybe we need to separate things out further for those particular audiences. Which i think means a more interesting, exciting beginning (maybe assume something that would bring someone to try MSAL for the first time), then separate out into these audience groups:
- new to msal
- i've used msal v2, what's new in v3 so i can get unblocked and move forward w/latest and greatest
- i've used adal and am moving to msal v3
- i'm passionate about identity and want to learn why the team moved from v2 to v3 and all the nitty gritty details

I think most of our users are in #1 and #2 (let's get moving on v3), so i think that should be the focus of the blog post. What do people need to do to move from v2 to v3, then why should someone move to v3 (what features are there?)...then I think the history of the why we have v3 could be in a separate section below all that or a separate post. 

If i were a dev, i'd want code snippets first and how to address the new build errors i have when updating to v3. then, if/when i have time, i might be interested in the why behind these things, and i will have to read more of the post.

Also, i think we need to tell people where to go to give feedback.

---
Refers to: msal-3x-blog.md:4 in 7461abd. [](commit_id = 7461abd13fea44bb9cb457be6b8ea62a4dfe0540, deletion_comment = False)

**Comment by henrik-me** [comment]
> }

with the next release we are removing merge. should this be updated already now?

---
Refers to: msal-3x-blog.md:382 in 7461abd. [](commit_id = 7461abd13fea44bb9cb457be6b8ea62a4dfe0540, deletion_comment = False)

**Comment by henrik-me** [comment]
Generally the stuff on merge should be updated. though perhaps not until we actually release the changes. not sure about that though

**Comment by henrik-me** [comment]
I think the content is great. While long it talks about all the interesting points.

**Pull request merged**
