### PR TITLE
create an MSAL specific contributor wiki entry

### PR DESCRIPTION
**Pull request by devigned**
Point to the new MSAL specific Contributor Overview and build / test setup. This should help contributors to MSAL.NET be more successful setting up the project for the first time. It should also help to delineate the MSAL repo from the ADAL repo.

Please review the contributor overview and build / test guidance wiki pages to ensure validity.

/cc @jmprieur

### CODE REVIEW

**Comment by jmprieur** [comment]
Amazing! thanks @devigned !

**Comment by trwalke** [comment]
This link (https://github.com/username/microsoft-authentication-library-for-dotnet.git) at the bottom of the page doesn't go anywhere. Where should it go?

**Comment by devigned** [comment]
@trwalke it shouldn't go anywhere. It is exemplar. It show that your "username" will be in the name of the fork you create.

**Comment by devigned** [comment]
@trwalke thank you for the feedback. I've updated the URI so that it is no longer a hyperlink.

**Pull request merged**
