### PR TITLE
Add InternalsVisible for Extensions projects

### PR DESCRIPTION
**Pull request by MarkZuber**
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/975

### CODE REVIEW

**Comment by MarkZuber** [comment]
> LGTM (even if I don't know yet why this will be needed. I thought that we'd want these packages to be on top of the public API ?)

We want the cache implementations to be able to get to the logger which isn't available in the public API.

**Comment by bgavrilMS** [comment]
If it's just for the logger, it will make sense to expose it as part of our extensibility story. ICustomWebUi will want to use it as well, and also @jmprieur 's ASP.NET extensions.

**Comment by henrik-me** [comment]
Agree. I would also prefer that we don't do this and rather exposes what the extensibility story needs

---
In reply to: [472876067](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/976#issuecomment-472876067) [](ancestors = 472876067)

**Comment by MarkZuber** [comment]
> Agree. I would also prefer that we don't do this and rather exposes what the extensibility story needs
> 
> In reply to: [472876067](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/976#issuecomment-472876067) [](ancestors = 472876067)

This is the first I've heard on the extensibility story related to exposing things like logging.  Do we have a doc or plan for this as part of msal 3.x preview since it's public API impacting?  VS will need this soon for their cache implementation so we need to get that solution in place now if we're not going to do exposure of internals to this particular library.

**Pull request merged**
