### PR TITLE
Update Xamarin

### PR DESCRIPTION
**Pull request by MichelZ**
Working on #2912 

This gets rid of some Xamarin MinPlatformVersion warnings

### CODE REVIEW

**Review by pmaytak — COMMENTED** [review]
Seems like there are a few other projects that can be upgraded. Otherwise, we get package downgrade warnings.
image

**Comment by bgavrilMS** [comment]
To be honest, I would not work on these. Xamarin is on its way out. Can't wait to GC Maui, wait for 1 year and remove Xamarin support (probably wishful thinking, but one is allowed to dream).

**Comment by MichelZ** [comment]
> To be honest, I would not work on these. Xamarin is on its way out. Can't wait to GC Maui, wait for 1 year and remove Xamarin support (probably wishful thinking, but one is allowed to dream).

Good one :)
Things tend to stick around unfortunately. It will depend on how well MAUI works

**Comment by bgavrilMS** [comment]
> 

Well, MAUI is an evolution of Xamarin, I'm can only assume Xamarin will be put in maintenance mode (not official MSFT position, I did not chat to the Maui folks about this). Especially as .NET is moving so fast nowadays.

**Comment by bgavrilMS** [comment]
@MichelZ - if you want to help with some more interesting stuff, we have a label "Good First Issue" - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

Right now there are only 2 issues there, but I can add some more.

**Review by SameerK-MSFT — CHANGES_REQUESTED** [review]
I would not upgrade Intune project. Intune SDK has some dependencies. Also, we need to support the minimum Android version of 10.0. Not below that.

**Comment by MichelZ** [comment]
> I would not upgrade Intune project. Intune SDK has some dependencies. Also, we need to support the minimum Android version of 10.0. Not below that.

Readme says:
`Mono Android 9.0`

So I should just ignore that?
(I might try again to get this working)

**Pull request closed without merging**
